import numpy as np
marks = np.array([[78,84,90],[45,80,56],[42,75,67],[76,90,67],[45,90,73]])
print("student marks:\n")
print(marks)
student_avg = np.mean(marks, axis=1)
print("\naverage marks of each student:")
print(student_avg)
subject_avg = np.mean(marks, axis=0)
print("\n subject-wise average:")
print(subject_avg)
highest = np.max(marks)
print (highest)
lowest = np.min(marks)
print("\n lowest marks:")
print(lowest)
topper = np.argmax(student_avg)
print("\ntopper student index:")
print(topper)
failed = np.where(student_avg < 40)
print("\n failed student index:")
print(failed)